version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "4001:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: team_polls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  redis:
    image: redis:7
    ports:
      - "6380:6379"

volumes:
  pgdata:
