version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "4001:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: # This passes variables from your local .env (or shell) to the Docker build process
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_WS_BASE_URL: ${VITE_WS_BASE_URL}
    ports:
      - "8080:3000"
    depends_on:
      - backend
    # No need for env_file here, as variables are baked in at build time

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: team_polls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    

  redis:
    image: redis:7
    ports:
      - "6380:6379"

volumes:
  pgdata: